### ISSUE TITLE
"up to your home dir"

### ISSUE THREAD

**Issue by tombosc** [jenterkin/vim-autosource#22]
Hey, first of all, thanks for your work! 

It took me some time to realize that the plug-in "didn't work" because my code is located not in a subdir of `$HOME`. I basically replaced the 2 occurrences of `$HOME` with `'/'` and now it seems to work great for me. Is there a reason why `$HOME` is preferred (security? speed?). If `'/'` is wrong for some reason, maybe it could be customizable via a global variable?

Thanks :)

**Comment by jenterkin** [comment]
Hey @tombosc, sorry for the late reply. I was out enjoying my holidays and hope you did the same :)

> Is there a reason why `$HOME` is preferred (security? speed?).

This has more to do with the *nix convention that all user configuration should be in your home directory. Basically I can't think of a compelling reason to check for user configuration outside of `~`. May I ask what the use case of having a vim conf outside of your home directory is?

I would be hesitant to make this default functionality, but I would be open to implementing this as an option (I probably won't have time this week) or accepting a PR for it.

**Comment by fjfnaranjo** [comment]
Hi there! Thanks for the plugin. I had the same use-case as OP and I fixed it using the same approach :P

> May I ask what the use case of having a vim conf outside of your home directory is?

I have a project in `/mounts/network_share/Repositories/my_project` (not the actual name, but outside `/home/foo`).

**Comment by jenterkin** [comment]
@fjfnaranjo That's super reasonable. I just merged a pr to address this. All you need to do is set `g:autosource_search_from_root` to `1` :)

https://github.com/jenterkin/vim-autosource#gautosource_search_from_root

**Comment by jenterkin** [comment]
Oh yeah. @tombosc @fjfnaranjo: Since you set _both_ occurrences of `$HOME` to `/` you had the plugin looking at `/.autosource_hashes` (unless you overrode that path via `g:autosource_hashdir`). Assuming you did not set `g:autosource_hashdir`, there are two things that could have happened here:

1. You ran it with `sudo` or as a user that had permissions to write to `/`. In this case it would have created `/.autosource_hashes` and stored your hashes there. This is fine, but you may want to delete the directory and optionally move the hashes to `~/.autosource_hashes`.
2. You did _not_ use `sudo` and your user did _not_ have write permissions on `/`. In this case nothing happened, but the plugin would not be able to store the hashes, meaning that you would have been prompted to re-approve your conf files each time, even if you already approved them. This is annoying, but fixed as long as you revert the change.

**Comment by fjfnaranjo** [comment]
Thanks for the patch!

About your warning: yes, it happened as you said :P I did a full replace of $HOME (%s/home/bla) and saw more than 2 replacements but I didn't care a that time. Then I found the problem and had to fix it.

**Comment by fjfnaranjo** [comment]
Hey, sorry to bother you again, but I had to remove this exit condition or the AutoSource command exists immediately:

https://github.com/jenterkin/vim-autosource/blob/03f4ae0ad918b23cb8305abca05e94b78f5d62d3/plugin/autosource.vim#L165-L168

I was scratching my mind about this because I can't understand its purpose...

**Comment by fjfnaranjo** [comment]
Ok, looks like the exit condition for a while in an older version of the function.

https://github.com/jenterkin/vim-autosource/blob/d250f521868a2ef79760c77534a9c5715f45ac11/plugin/autosource.vim#L85-L89

Today, this is done further down:

https://github.com/jenterkin/vim-autosource/blob/03f4ae0ad918b23cb8305abca05e94b78f5d62d3/plugin/autosource.vim#L176-L178

Sending a PR to remove it.

**Comment by jenterkin** [comment]
Hey no worries! I appreciate the feedback. Thanks for the contribution.
